<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0 (Python 3.12.0 on win32)" generated="2024-01-30T22:44:39.715212" rpa="false" schemaversion="5">
<suite id="s1" name="Testing Database" source="C:\Users\ivich\Desktop\DevOps_Oct2023_TeamC_Assignment\testing_database.robot">
<test id="s1-t1" name="Example SQLite Test" line="12">
<kw name="Connect To Database Using Custom Params" owner="DatabaseLibrary" type="SETUP">
<msg time="2024-01-30T22:44:39.745632" level="INFO">Executing : Connect To Database Using Custom Params : sqlite3.connect(db_api_2.connect(database= '/instance/{DB_NAME}'))</msg>
<msg time="2024-01-30T22:44:39.746716" level="FAIL">OperationalError: unable to open database file</msg>
<arg>sqlite3</arg>
<arg>database= '/instance/{DB_NAME}'</arg>
<doc>Loads the DB API 2.0 module given `dbapiModuleName` then uses it to
connect to the database using the map string `db_connect_string`
(parsed as a list of named arguments).</doc>
<status status="FAIL" start="2024-01-30T22:44:39.742631" elapsed="0.004085">OperationalError: unable to open database file</status>
</kw>
<kw name="Disconnect From Database" owner="DatabaseLibrary" type="TEARDOWN">
<msg time="2024-01-30T22:44:39.747649" level="INFO">Executing : Disconnect From Database</msg>
<msg time="2024-01-30T22:44:39.747649" level="INFO">No open database connection to close</msg>
<doc>Disconnects from the database.</doc>
<status status="PASS" start="2024-01-30T22:44:39.747649" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2024-01-30T22:44:39.741625" elapsed="0.006868">Setup failed:
OperationalError: unable to open database file</status>
</test>
<status status="FAIL" start="2024-01-30T22:44:39.716122" elapsed="0.034046"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Testing Database">Testing Database</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
